// General Error
//
export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";

// AUTH
//
export const AUTH_ERRORS = "AUTH_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const FORGET_STATUS = "FORGET_STATUS";
export const CREATE_STATUS = "CREATE_STATUS";
export const RESET_CREATE_STATUS = "RESET_CREATE_STATUS";
export const RESET_FORGET_STATUS = "RESET_FORGET_STATUS";
export const RESET_STATUS = "RESET_STATUS";
export const RESET_RESET_STATUS = "RESET_RESET_STATUS";

// PROFILE
export const GET_PROFILE_INFO = "GET_PROFILE_INFO";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const SET_CURRENT_PERSONAL = "SET_CURRENT_PERSONAL";
export const PERSONAL_UPDATING_STATUS = "PERSONAL_UPDATING_STATUS";
export const RESET_PERSONAL_UPDATING_STATUS = "RESET_PERSONAL_UPDATING_STATUS";
export const OVERIDE_GREENLIGHT = "OVERIDE_GREENLIGHT";
export const OVERIDE_REDLIGHT = "OVERIDE_REDLIGHT";

// LLMCHATBOT
// DEEPSEEK
export const SET_LLM_RESPONSE = "SET_LLM_RESPONSE";
export const RESET_LLM_RESPONSE = "RESET_LLM_RESPONSE";
export const LLM_ERRORS = "LLM_ERRORS";